(define (read-words)
  (let loop ((char (read-char))
             (cur-st "")
             (xs '()))
    (if (eof-object? char)
        (if (not (equal? cur-st ""))
            (append xs (list cur-st))
            xs)
        (if (char-whitespace? char)
            (if (not (equal? cur-st ""))
                (loop (read-char) "" (append xs (list cur-st)))
                (loop (read-char) "" xs))
            (loop (read-char) (list->string (append (string->list cur-st) (list char))) xs)))))
