#!/bin/python3

import sys

def main():
    if len(sys.argv) != 2:
        print("Error: Enter the path to the file")
        sys.exit(1)
    
    file_path = sys.argv[1]

    try:
        with open(file_path, 'r') as f:
            lines = f.readlines()
        with open(file_path, 'w') as file:
            i = 1
            for line in lines:
                if line.strip():
                    file.write(f"{i}\t{line.rstrip()}\n")
                    i += 1
                else:
                    file.write(f"{line.rstrip()}\n")
                    
    except Exception as E:
        print(f"Error: {E}")
        sys.exit(1)


if __name__ == '__main__':
    main()
