#!/bin/bash

counter() {
   cnt=0
   while read -r line; do
      if [[ -n "$line" ]]; then
         cnt=$((cnt+1))
      fi
   done < "$1"

   echo "$cnt"
}

rec() {
   if [ -d "$1" ]; then
      ls "$1" | while read name; do
         rec "$1/$name"
      done
   else
      if [[ "$1" == *.c || "$1" == *.h ]]; then
         cnt_rec=$(counter "$1")
         count=$((count+cnt_rec))
      fi
   fi
}

count=0
rec "$1"

echo "Count: $count"

